name: Automated Testing

on:
  push:
    branches-ignore:
      - 'documentation'
    paths:
      - 'version.cmake'
      - 'tests/**'

jobs:
  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
    - name: "Clone"
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: "Install Prerequisites"
      shell: bash
      run: |
        sudo apt-get install build-essential cmake

    - name: "Run Tests"
      shell: bash
      run: |
        cmake -Htests -Bbuild/tests

